/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as DocumentationRouteImport } from "./app/documentation"
import { Route as CookbookRouteImport } from "./app/cookbook"
import { Route as IndexRouteImport } from "./app/index"

const DocumentationRoute = DocumentationRouteImport.update({
  id: "/documentation",
  path: "/documentation",
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: "/cookbook",
  path: "/cookbook",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/cookbook": typeof CookbookRoute
  "/documentation": typeof DocumentationRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cookbook": typeof CookbookRoute
  "/documentation": typeof DocumentationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/cookbook": typeof CookbookRoute
  "/documentation": typeof DocumentationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/cookbook" | "/documentation"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/cookbook" | "/documentation"
  id: "__root__" | "/" | "/cookbook" | "/documentation"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRoute
  DocumentationRoute: typeof DocumentationRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/documentation": {
      id: "/documentation"
      path: "/documentation"
      fullPath: "/documentation"
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cookbook": {
      id: "/cookbook"
      path: "/cookbook"
      fullPath: "/cookbook"
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRoute,
  DocumentationRoute: DocumentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
