/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as ExplorerRouteImport } from "./app/explorer"
import { Route as DocumentationRouteImport } from "./app/documentation"
import { Route as DemoRouteImport } from "./app/demo"
import { Route as IndexRouteImport } from "./app/index"

const ExplorerRoute = ExplorerRouteImport.update({
  id: "/explorer",
  path: "/explorer",
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: "/documentation",
  path: "/documentation",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: "/demo",
  path: "/demo",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/demo" | "/documentation" | "/explorer"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/demo" | "/documentation" | "/explorer"
  id: "__root__" | "/" | "/demo" | "/documentation" | "/explorer"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocumentationRoute: typeof DocumentationRoute
  ExplorerRoute: typeof ExplorerRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/explorer": {
      id: "/explorer"
      path: "/explorer"
      fullPath: "/explorer"
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/documentation": {
      id: "/documentation"
      path: "/documentation"
      fullPath: "/documentation"
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo": {
      id: "/demo"
      path: "/demo"
      fullPath: "/demo"
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocumentationRoute: DocumentationRoute,
  ExplorerRoute: ExplorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
