/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as ExplorerRouteImport } from "./app/explorer"
import { Route as DocumentationRouteImport } from "./app/documentation"
import { Route as DemoRouteImport } from "./app/demo"
import { Route as IndexRouteImport } from "./app/index"
import { Route as ExplorerUAddressRouteImport } from "./app/explorer/u.$address"
import { Route as ExplorerDAddressRouteImport } from "./app/explorer/d.$address"

const ExplorerRoute = ExplorerRouteImport.update({
  id: "/explorer",
  path: "/explorer",
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: "/documentation",
  path: "/documentation",
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: "/demo",
  path: "/demo",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerUAddressRoute = ExplorerUAddressRouteImport.update({
  id: "/u/$address",
  path: "/u/$address",
  getParentRoute: () => ExplorerRoute,
} as any)
const ExplorerDAddressRoute = ExplorerDAddressRouteImport.update({
  id: "/d/$address",
  path: "/d/$address",
  getParentRoute: () => ExplorerRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRouteWithChildren
  "/explorer/d/$address": typeof ExplorerDAddressRoute
  "/explorer/u/$address": typeof ExplorerUAddressRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRouteWithChildren
  "/explorer/d/$address": typeof ExplorerDAddressRoute
  "/explorer/u/$address": typeof ExplorerUAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/demo": typeof DemoRoute
  "/documentation": typeof DocumentationRoute
  "/explorer": typeof ExplorerRouteWithChildren
  "/explorer/d/$address": typeof ExplorerDAddressRoute
  "/explorer/u/$address": typeof ExplorerUAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/demo"
    | "/documentation"
    | "/explorer"
    | "/explorer/d/$address"
    | "/explorer/u/$address"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/demo"
    | "/documentation"
    | "/explorer"
    | "/explorer/d/$address"
    | "/explorer/u/$address"
  id:
    | "__root__"
    | "/"
    | "/demo"
    | "/documentation"
    | "/explorer"
    | "/explorer/d/$address"
    | "/explorer/u/$address"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocumentationRoute: typeof DocumentationRoute
  ExplorerRoute: typeof ExplorerRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/explorer": {
      id: "/explorer"
      path: "/explorer"
      fullPath: "/explorer"
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/documentation": {
      id: "/documentation"
      path: "/documentation"
      fullPath: "/documentation"
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/demo": {
      id: "/demo"
      path: "/demo"
      fullPath: "/demo"
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/explorer/u/$address": {
      id: "/explorer/u/$address"
      path: "/u/$address"
      fullPath: "/explorer/u/$address"
      preLoaderRoute: typeof ExplorerUAddressRouteImport
      parentRoute: typeof ExplorerRoute
    }
    "/explorer/d/$address": {
      id: "/explorer/d/$address"
      path: "/d/$address"
      fullPath: "/explorer/d/$address"
      preLoaderRoute: typeof ExplorerDAddressRouteImport
      parentRoute: typeof ExplorerRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerDAddressRoute: typeof ExplorerDAddressRoute
  ExplorerUAddressRoute: typeof ExplorerUAddressRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerDAddressRoute: ExplorerDAddressRoute,
  ExplorerUAddressRoute: ExplorerUAddressRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocumentationRoute: DocumentationRoute,
  ExplorerRoute: ExplorerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
